
---
  - name: Install MySQL  basic software
    yum: name={{ item }}  state=latest
    with_items:
      - ncurses
      - ncurses-devel
      - bison
      - bison-devel
      - cmake 
      - gcc 
      - gcc-c++ 
      - libtool 
      - autoconf 
      - patch 
      - unzip 
      - automake 
      - libtool-ltdl-devel 
      - libtool-ltdl 
      - libmcrypt 
      - libmcrypt-devel 
      - libpng 
      - libpng-devel 
      - libjpeg-devel 
      - openssl 
      - openssl-devel 
      - curl-devel 

  - name: create MySQL Group
    group: name=mysql gid=27

  - name: create MySQL User
    user: name=mysql shell=/sbin/nologin createhome=no uid=27 group=mysql

  - name: mkdir /home/mydata
    command: mkdir -p /home/mydata 

  - name: Set Link /mydata
    file: src=/home/mydata dest=/mydata  owner=mysql group=mysql state=link 

  - name: get MySQL source
    #copy: src=mysql-5.1.73 dest=/tmp/mysql-5.1.73 
    unarchive: src=mysql-5.1.73.tar.gz dest=/tmp/ copy=yes  
    tags: fetchmysql

  - name: configuring
    script: configmysql.sh > /tmp/mysql_install.log 2>&1
    tags: configure

  - name: make mysql-5.1.73
    script: makemysql.sh >> /tmp/mysql_install.log 2>&1
    tags: makemysql

  - name: makeinstallmysql
    script: makeinstallmysql.sh >> /tmp/mysql_install.log 2>&1
    tags: makeinstallmysql 

  - name: set mysql config file
    template: src=my.cnf.j2 dest=/mydata/data/my.cnf
    tags: mycnf

  - name: linke my.cnf
    file: src=/mydata/data/my.cnf dest=/etc/my.cnf state=link
    tags: linkmycnf    

  - name: set owner
    file: path=/mydata/data owner=mysql group=mysql mode=0755 recurse=yes
    tags: setowner

  - name: mysql_install_db
    script: mysql_install_db.sh >> /tmp/mysql_install.log 2>&1
    tags: mysql_install_db

  - name: set mysql servces
    command:  cp -f /tmp/mysql-5.1.73/support-files/mysql.server  /etc/rc.d/init.d/mysqld 
    tags: setinit

  - name: set mysqld
    file: path=/etc/init.d/mysqld owner=root group=root mode=0755
    tags: setmysqldowner

  - name: add init.d for mysql
    service: name=mysqld state=started enabled=yes
    tags: setserv

